[package]
name = "candle-mnist-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.28"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
